# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

parameters:
  - name: Branch
    type: string

steps:
- task: PowerShell@2
  displayName: Generate command metadata
  inputs:
    targetType: inline
    pwsh: true
    script: |
      . $(System.DefaultWorkingDirectory)/tools/PostGeneration/NewCommandMetadata.ps1 -SourcePath "$(System.DefaultWorkingDirectory)/src/" -IncludePermissions -Debug

- task: PowerShell@2
  displayName: "Configure user"
  inputs:
    targetType: "inline"
    script: |
      git config --global user.email "GraphTooling@service.microsoft.com"
      git config --global user.name "Microsoft Graph DevX Tooling"

- task: Bash@3
  displayName: Push command metadata
  enabled: true
  env:
    GITHUB_TOKEN: $(GITHUB_TOKEN)
  inputs:
    targetType: inline
    script: |
      git status
      git add "$(System.DefaultWorkingDirectory)/src/Authentication/Authentication/custom/common/MgCommandMetadata.json"
      git commit -m 'Add generated MgCommandMetadata.json. [run ci]'
      git push --set-upstream origin $(Branch)
      git status